const KEY='program-rimba-pwa-v1';
const A=['Weighted Push-Up','Goblet Squat','One-Arm Row','Shoulder Press','Plank'];
const B=['RDL','Lunges','Feet-Elevated Push-Up','Curl','Slow Leg Raise','Band Lat Pulldown','Band Face Pull'];
const seed={measurements:[['2026-06-21',69.1,90],['2026-07-19',68.9,89.5],['2026-08-08',68.7,91],['2026-08-16',68.3,90.5],['2026-08-19',68.1,89],['2026-08-23',67.7,89],['2026-08-30',68,89.5],['2026-09-06',69.6,90],['2026-09-13',68.7,90],['2026-09-20',68.3,88]],workouts:[],activities:[]};
let state=load(), tab='dashboard', modal=null;
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.measurements)?x:cloneSeed()}catch{return cloneSeed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n,d=1){return n==null||Number.isNaN(+n)?'—':(+n).toFixed(d).replace('.',',')}
function latest(){return [...state.measurements].sort((a,b)=>b[0].localeCompare(a[0]))[0]}
function startM(){return state.measurements[0]}
function month(){const d=new Date();const s=new Date('2026-09-19');return Math.max(1,Math.floor((d-s)/2592e6)+4)}
function app(){document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand">Program Rimba</div><div class="sub">Body recomposition • Month ${month()}</div></div><main class="view">${tab==='dashboard'?dashboard():tab==='workout'?workout():tab==='progress'?progress():settings()}</main><div class="bottom"><div class="nav">${nav('dashboard','🏠','Dashboard')}${nav('workout','🏋️','Latihan')}${nav('progress','📈','Progress')}${nav('settings','⚙️','Data')}</div></div>${modal?modalHtml():''}</div>`;drawCharts();}
function nav(k,i,t){return `<button class="${tab===k?'active':''}" onclick="tab='${k}';modal=null;app()"><span class="ico">${i}</span>${t}</button>`}
function dashboard(){let l=latest(),s=startM(),delta=(l?.[1]??0)-(s?.[1]??0),wd=state.workouts.length, act=state.activities.length;return `<div class="grid"><div class="metric"><span>Berat terbaru</span><b>${fmt(l?.[1])} kg</b><small class="${delta<=0?'good':'bad'}">${delta>0?'+':''}${fmt(delta)} kg dari awal</small></div><div class="metric"><span>Lingkar perut</span><b>${fmt(l?.[2])} cm</b><small class="good">${fmt((l?.[2]??0)-(s?.[2]??0))} cm dari awal</small></div></div><div class="card"><div class="row"><div><b>Month ${month()}</b><div class="muted">Fokus: konsistensi + progressive overload</div></div><span class="pill">Program Rimba</span></div><div class="section-title">Snapshot</div><div class="grid"><div><b>${wd}</b><div class="smallnote">sesi latihan</div></div><div><b>${act}</b><div class="smallnote">aktivitas</div></div></div></div><div class="section-title">Coach insight</div><div class="card"><b>88 cm lingkar perut — milestone penting.</b><p class="muted">Dari 90 cm pada 21 Jun menjadi 88 cm pada 20 Sep. Berat tetap relatif stabil, jadi lihat tren beberapa minggu, bukan satu angka harian.</p><p class="muted">Pertahankan latihan beban, protein yang realistis, tidur, dan kontrol kopi manis. Tidak perlu mengejar penurunan ekstrem.</p></div><div class="section-title">Aksi cepat</div><div class="actions"><button class="btn" onclick="openWorkout()">+ Latihan</button><button class="btn secondary" onclick="openMeasure()">+ Ukur</button><button class="btn secondary" onclick="openActivity()">+ Aktivitas</button></div>`}
function workout(){let ws=[...state.workouts].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="row"><div><h2 style="margin:8px 0 0">Latihan</h2><div class="muted">Full Body A / B</div></div><button class="btn" onclick="openWorkout()">+ Latihan</button></div><div class="section-title">Riwayat</div><div class="list">${ws.length?ws.map((w,i)=>`<div class="item"><div class="row"><div><h4>${esc(w.type)} <span class="pill">${esc(w.date)}</span></h4><p>${w.exercises.map(e=>`${esc(e.name)} ${e.sets.length}×`).join(' • ')}</p>${w.note?`<p>${esc(w.note)}</p>`:''}</div><div class="actions"><button class="btn small secondary" onclick="editWorkout(${i})">Edit</button><button class="btn small danger" onclick="delWorkout(${i})">Hapus</button></div></div></div>`).join(''):`<div class="empty">Belum ada sesi latihan. Yuk mulai catat sesi berikutnya.</div>`}</div>`}
function progress(){let m=[...state.measurements].sort((a,b)=>a[0].localeCompare(b[0]));return `<div class="row"><div><h2 style="margin:8px 0 0">Progress</h2><div class="muted">BB dan lingkar perut</div></div><button class="btn" onclick="openMeasure()">+ Ukur</button></div><div class="section-title">Grafik berat badan</div><canvas id="weightChart" width="700" height="260"></canvas><div class="section-title">Grafik lingkar perut</div><canvas id="waistChart" width="700" height="260"></canvas><div class="section-title">Riwayat pengukuran</div><div class="list">${m.slice().reverse().map((x,i)=>`<div class="item"><div class="row"><div><b>${esc(x[0])}</b><p>BB ${fmt(x[1])} kg • Lingper ${fmt(x[2])} cm</p></div><button class="btn small danger" onclick="delMeasure('${x[0]}')">Hapus</button></div></div>`).join('')}</div>`}
function settings(){return `<h2 style="margin:8px 0">Data & Backup</h2><div class="card"><b>Data tersimpan di HP</b><p class="muted">Versi ini memakai localStorage, jadi data utama tetap berada di browser/perangkat. Backup JSON dianjurkan secara berkala.</p><div class="actions"><button class="btn" onclick="backup()">Export JSON</button><button class="btn secondary" onclick="document.getElementById('restore').click()">Import JSON</button><input id="restore" type="file" accept="application/json" style="display:none" onchange="restore(this)"></div></div><div class="card"><b>Program saat ini</b><p class="muted">Month ${month()} • ${state.measurements.length} pengukuran • ${state.workouts.length} latihan • ${state.activities.length} aktivitas</p></div><div class="card"><b>Reset</b><p class="muted">Menghapus semua data lokal dan kembali ke data awal.</p><button class="btn danger" onclick="resetAll()">Reset data</button></div>`}
function modalHtml(){return `<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet">${modal.type==='measure'?measureForm():modal.type==='activity'?activityForm():workoutForm()}</div></div>`}
function closeModal(){modal=null;app()}
function measureForm(){let x=modal.edit;return `<div class="row"><h3>${x?'Edit':'Tambah'} pengukuran</h3><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="field"><label>Tanggal</label><input id="mdate" type="date" value="${x?.[0]||new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Berat badan (kg)</label><input id="mweight" inputmode="decimal" value="${x?.[1]??''}"></div><div class="field"><label>Lingkar perut (cm)</label><input id="mwaist" inputmode="decimal" value="${x?.[2]??''}"></div><button class="btn" onclick="saveMeasure()">Simpan</button>`}
function activityForm(){return `<div class="row"><h3>Tambah aktivitas</h3><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="field"><label>Tanggal</label><input id="adate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Jenis</label><select id="atype"><option>Recovery Upper</option><option>Jalan Kaki</option><option>Futsal</option><option>Recovery/Aktivitas Ringan</option><option>Lainnya</option></select></div><div class="field"><label>Catatan</label><textarea id="anote" rows="3"></textarea></div><button class="btn" onclick="saveActivity()">Simpan</button>`}
function workoutForm(){let type=modal?.edit?.type||'Full Body A', exs=modal?.edit?.exercises||((type==='Full Body B'?B:A).map(n=>({name:n,sets:[{load:'',reps:''},{load:'',reps:''},{load:'',reps:''}]})));return `<div class="row"><h3>${modal.edit?'Edit':'Tambah'} latihan</h3><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="field"><label>Tanggal</label><input id="wdate" type="date" value="${modal?.edit?.date||new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Program</label><select id="wtype" onchange="changeExerciseForm()"><option ${type==='Full Body A'?'selected':''}>Full Body A</option><option ${type==='Full Body B'?'selected':''}>Full Body B</option></select></div><div id="exerciseBox">${exerciseInputs(exs)}</div><div class="field"><label>Catatan</label><textarea id="wnote" rows="3">${esc(modal?.edit?.note||'')}</textarea></div><button class="btn" onclick="saveWorkout()">Simpan sesi</button>`}
function exerciseInputs(exs){return exs.map((e,ei)=>`<div class="sets"><b>${esc(e.name)}</b><div id="sets-${ei}">${e.sets.map((s,si)=>`<div class="setrow"><span>${si+1}</span><input class="load" data-e="${ei}" placeholder="kg" value="${esc(s.load)}"><input class="reps" data-e="${ei}" placeholder="reps" value="${esc(s.reps)}"><button class="btn small secondary" onclick="this.parentElement.remove()">×</button></div>`).join('')}</div><button class="btn small secondary" onclick="addSet(${ei})">+ set</button></div>`).join('')}
function changeExerciseForm(){let t=document.getElementById('wtype').value;document.getElementById('exerciseBox').innerHTML=exerciseInputs((t==='Full Body B'?B:A).map(n=>({name:n,sets:[{load:'',reps:''},{load:'',reps:''},{load:'',reps:''}]})))}
function addSet(ei){let box=document.getElementById('sets-'+ei), n=box.children.length;box.insertAdjacentHTML('beforeend',`<div class="setrow"><span>${n+1}</span><input class="load" data-e="${ei}" placeholder="kg"><input class="reps" data-e="${ei}" placeholder="reps"><button class="btn small secondary" onclick="this.parentElement.remove()">×</button></div>`)}
function openMeasure(){modal={type:'measure'};app()}function openActivity(){modal={type:'activity'};app()}function openWorkout(){modal={type:'workout'};app()}
function editWorkout(i){let ws=[...state.workouts].sort((a,b)=>b.date.localeCompare(a.date));modal={type:'workout',edit:JSON.parse(JSON.stringify(ws[i]))};app()}
function saveMeasure(){let d=document.getElementById('mdate').value,w=parseFloat(document.getElementById('mweight').value.replace(',','.')),wa=parseFloat(document.getElementById('mwaist').value.replace(',','.'));if(!d||!isFinite(w)||!isFinite(wa)||w<20||w>300||wa<30||wa>200)return toast('Cek tanggal, BB, dan lingkar perut');state.measurements=state.measurements.filter(x=>x[0]!==d);state.measurements.push([d,w,wa]);state.measurements.sort((a,b)=>a[0].localeCompare(b[0]));save();closeModal();toast('Pengukuran tersimpan')}
function delMeasure(d){if(!confirm('Hapus pengukuran '+d+'?'))return;state.measurements=state.measurements.filter(x=>x[0]!==d);save();app()}
function saveActivity(){let d=document.getElementById('adate').value,t=document.getElementById('atype').value,n=document.getElementById('anote').value.trim();if(!d)return toast('Tanggal wajib diisi');state.activities.push({date:d,type:t,note:n});save();closeModal();toast('Aktivitas tersimpan')}
function saveWorkout(){let date=document.getElementById('wdate').value,type=document.getElementById('wtype').value;let names=type==='Full Body B'?B:A, exs=names.map((name,ei)=>{let rows=[...document.querySelectorAll(`.load[data-e="${ei}"]`)].map((x,i)=>({load:x.value.trim(),reps:document.querySelectorAll(`.reps[data-e="${ei}"]`)[i]?.value.trim()||''})).filter(x=>x.load!==''||x.reps!=='');return {name,sets:rows}}).filter(e=>e.sets.length);let note=document.getElementById('wnote').value.trim();if(!date||!exs.length)return toast('Isi tanggal dan minimal satu set');let obj={date,type,exercises:exs,note};if(modal.edit){let target=modal.edit;let idx=state.workouts.findIndex(x=>x===target);if(idx<0){idx=state.workouts.findIndex(x=>x.date===target.date&&x.type===target.type)}if(idx>=0)state.workouts[idx]=obj;else state.workouts.push(obj)}else state.workouts.push(obj);save();closeModal();toast('Sesi latihan tersimpan')}
function delWorkout(i){let ws=[...state.workouts].sort((a,b)=>b.date.localeCompare(a.date));let target=ws[i];if(!confirm('Hapus sesi ini?'))return;state.workouts=state.workouts.filter(x=>x!==target);save();app()}
function backup(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ProgramRimba-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
function restore(inp){let f=inp.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.measurements)||!Array.isArray(x.workouts)||!Array.isArray(x.activities))throw 0;if(!confirm('Ganti data saat ini dengan backup ini?'))return;state=x;save();app();toast('Restore berhasil')}catch{toast('File backup tidak valid')}};r.readAsText(f)}
function resetAll(){if(!confirm('Hapus semua data lokal?'))return;state=cloneSeed();save();app()}
function toast(s){let d=document.createElement('div');d.className='toast';d.textContent=s;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function drawCharts(){if(tab!=='progress')return;setTimeout(()=>{draw('weightChart',1,'kg');draw('waistChart',2,'cm')},30)}
function draw(id,col,unit){let c=document.getElementById(id);if(!c)return;let ctx=c.getContext('2d'),D=devicePixelRatio||1,cw=c.clientWidth,ch=c.clientHeight;c.width=cw*D;c.height=ch*D;ctx.scale(D,D);let arr=[...state.measurements].sort((a,b)=>a[0].localeCompare(b[0])),vals=arr.map(x=>+x[col]);let min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.font='12px system-ui';ctx.fillStyle='#6b7280';ctx.fillText(`${fmt(vals[0])} ${unit}`,8,18);ctx.fillText(`${fmt(vals[vals.length-1])} ${unit}`,cw-80,18);ctx.strokeStyle='#111827';ctx.lineWidth=2;ctx.beginPath();arr.forEach((x,i)=>{let px=22+i*(cw-44)/Math.max(1,arr.length-1),py=ch-28-(vals[i]-min)/(max-min)*(ch-58);i?ctx.lineTo(px,py):ctx.moveTo(px,py);});ctx.stroke();arr.forEach((x,i)=>{let px=22+i*(cw-44)/Math.max(1,arr.length-1),py=ch-28-(vals[i]-min)/(max-min)*(ch-58);ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(px,py,3.5,0,Math.PI*2);ctx.fill();if(i===0||i===arr.length-1){ctx.fillStyle='#6b7280';ctx.fillText(x[0].slice(5),px-16,ch-8)}},30)}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
app();
